spring.application.name=ProductCatalogService_March2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/productcatalogservice_march2026
spring.datasource.username=root
spring.datasource.password=12345